[[redirects]]
  from = "/api"
  to = "$REACT_APP_SHOPIFY_URL"
  status = 200
  force = true
  headers = {X-From = "Netlify" , Access-Control-Allow-Origin = "*", X-Shopify-Storefront-Access-Token = "$process.env.REACT_APP_SHOPIFY",}