[[redirects]]
  from = "/api"
  to = "https://2span.myshopify.com/api/2020-04/graphql.json"
  status = 200
  force = true
  headers = {X-From = "Netlify" , "Access-Control-Allow-Origin": "*", "X-Shopify-Storefront-Access-Token": "d80ec663480008130c47c79bd5657cb4",}